// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	libcnb "github.com/buildpacks/libcnb"
	mock "github.com/stretchr/testify/mock"
)

// SBOMScanner is an autogenerated mock type for the SBOMScanner type
type SBOMScanner struct {
	mock.Mock
}

// ScanBuild provides a mock function with given fields: scanDir, formats
func (_m *SBOMScanner) ScanBuild(scanDir string, formats ...libcnb.SBOMFormat) {
	_va := make([]interface{}, len(formats))
	for _i := range formats {
		_va[_i] = formats[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, scanDir)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// ScanLaunch provides a mock function with given fields: scanDir, formats
func (_m *SBOMScanner) ScanLaunch(scanDir string, formats ...libcnb.SBOMFormat) {
	_va := make([]interface{}, len(formats))
	for _i := range formats {
		_va[_i] = formats[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, scanDir)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// ScanLayer provides a mock function with given fields: layer, scanDir, formats
func (_m *SBOMScanner) ScanLayer(layer libcnb.Layer, scanDir string, formats ...libcnb.SBOMFormat) {
	_va := make([]interface{}, len(formats))
	for _i := range formats {
		_va[_i] = formats[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, layer, scanDir)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
