// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	libcnb "github.com/buildpacks/libcnb/v2"
	mock "github.com/stretchr/testify/mock"
)

// SBOMScanner is an autogenerated mock type for the SBOMScanner type
type SBOMScanner struct {
	mock.Mock
}

// ScanBuild provides a mock function with given fields: scanDir, formats
func (_m *SBOMScanner) ScanBuild(scanDir string, formats ...libcnb.SBOMFormat) error {
	_va := make([]interface{}, len(formats))
	for _i := range formats {
		_va[_i] = formats[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, scanDir)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...libcnb.SBOMFormat) error); ok {
		r0 = rf(scanDir, formats...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ScanLaunch provides a mock function with given fields: scanDir, formats
func (_m *SBOMScanner) ScanLaunch(scanDir string, formats ...libcnb.SBOMFormat) error {
	_va := make([]interface{}, len(formats))
	for _i := range formats {
		_va[_i] = formats[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, scanDir)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...libcnb.SBOMFormat) error); ok {
		r0 = rf(scanDir, formats...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ScanLayer provides a mock function with given fields: layer, scanDir, formats
func (_m *SBOMScanner) ScanLayer(layer libcnb.Layer, scanDir string, formats ...libcnb.SBOMFormat) error {
	_va := make([]interface{}, len(formats))
	for _i := range formats {
		_va[_i] = formats[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, layer, scanDir)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(libcnb.Layer, string, ...libcnb.SBOMFormat) error); ok {
		r0 = rf(layer, scanDir, formats...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSBOMScanner creates a new instance of SBOMScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSBOMScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *SBOMScanner {
	mock := &SBOMScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
